### ISSUE TITLE
Redefined Constants if both `UD60x18` and `SD59x18` are imported

### ISSUE THREAD

**Issue by NicolaBernini** [PaulRBerg/prb-math#156]
In the Readme, it is said it is possible to import both the libraries 

```solidity
pragma solidity >=0.8.13;

import "@prb/math/SD59x18.sol";
import "@prb/math/UD60x18.sol";

```

However, this leads to redefined constants like for example 

```solidity
SD59x18 constant E = SD59x18.wrap(2_718281828459045235);
```

https://github.com/PaulRBerg/prb-math/blob/main/src/sd59x18/Constants.sol#L9

and 

```solidity
UD60x18 constant E = UD60x18.wrap(2_718281828459045235);
```

https://github.com/PaulRBerg/prb-math/blob/main/src/ud60x18/Constants.sol#L7

So apparently importing both libs is not possible

**Comment by PaulRBerg** [comment]
Great catch, Nicola!

The README does not explicitly say that you can both import, though. I simply put both imports there to show case how the imports looks like for both libraries - typically users need only one or the other.

Nonetheless, point well taken. I must rewrite to README to explain that users cannot import both libraries in the global scope.

What can be done, however, is something like this:

```solidity
import "@prb/math/SD59x18.sol" as SD;
import "@prb/math/UD60x18.sol" as UD;
```

And then you can use the `E` constants like this:

```solidity
function foo() pure {
    SD.E;
    UD.E;
}
```

Though if I were in your shoes, I would NOT use the technique above. Instead, I would import only specific symbols, like this:

```solidity
import { SD59x18 } from "@prb/math/SD59x18.sol";
import { UD60x18 } from "@prb/math/UD60x18.sol";
```

I have made a few improvements to the API recently, and now I actually no longer recommend importing the files in the global scope.

I will update the README!

**Comment by PaulRBerg** [comment]
Fixed via https://github.com/PaulRBerg/prb-math/commit/642a4c948daf51266564a445c9bfe7f4a228eae0.

**Comment by PaulRBerg** [comment]
Hi @NicolaBernini, did my answer above address your concern?
