### ISSUE TITLE
Incorrect uEXP2_MAX_INPUT for UD60x18 and SD59x18

### ISSUE THREAD

**Issue by syakunin** [PaulRBerg/prb-math#187]
### What version of PRBMath are you using?

4

### What version of Solidity are you using?

0.8.19

### Operating System

None

### Describe the bug

According to the function documentation `Common.exp2()` uses `192x64` fixed point format, which means that `x` maximum is 2^192 whereas `uEXP2_MAX_INPUT` value is `192e18 - 1` and not `2**192 - 1`.

**Comment by PaulRBerg** [comment]
The argument in `exp2` is the exponent, so it is correct that `uEXP2_MAX_INPUT` is `192e18 - 1`.
