### ISSUE TITLE
HardHat Instilation broken

### ISSUE THREAD

**Issue by kkoshiya** [PaulRBerg/prb-math#209]
### What version of PRBMath are you using?

4.0.1

### What version of Solidity are you using?

0.8.19

### Describe the bug

Hey community, I'm currently trying to get started using the prb-math package for my contracts via hardhat (I can't use foundry due to a different conflict). I was wondering if somebody could help me, for some reason my contract can't find the import. Thanks

**Comment by PaulRBerg** [comment]
hey @kkoshiya I am closing this issue in favor of the other discussion you have opened:

https://github.com/PaulRBerg/prb-math/discussions/208
