### ISSUE TITLE
Update EVM Version to `Shanghai`

### ISSUE THREAD

**Issue by smol-ninja** [PaulRBerg/prb-math#231]
### Describe the feature you would like

Use `shanghai` version of the EVM.

### Additional context

By setting `evm_version` to `shanghai`, the deployed bytecode of `PRBMath` will be more optimized because of `PUSH0` opcode. Thus I recommend changing the value of `evm_version` in [`foundry.toml`](https://github.com/PaulRBerg/prb-math/blob/main/foundry.toml).

**Comment by PaulRBerg** [comment]
Done in https://github.com/PaulRBerg/prb-math/commit/368168128017589c3085ed5aeacb0c328d743e69.
