### ISSUE TITLE
No method calls reported by hardhat-gas-reporter

### ISSUE THREAD

**Issue by cameel** [paulrberg/prb-math#70]
Hello! I'm interested in benchmarking the gas usage of specific methods to see how changes in the compiler affect overall gas usage of the library. To do this I'm simply adding `hardhat-gas-reporter` as a dependency and inserting an extra import into `hardhat.config.ts`. This is enough to get a nice gas report in most projects but here unfortunately for some reason the plugin only reports deployment costs.

I'm not sure what the cause is but I suspect it might have something to do with the unusual test structure. Test files export functions and there's a top-level file that executes those test functions.

Overall I'm not sure if the plugin has a bug or if PRBMath is just doing things the way that's not compatible with it. If it's the latter, it might be a good idea to adjust the code to make it compatible.

### How to reproduce
```bash
git clone https://github.com/paulrberg/prb-math
cd prb-math/
cp .env.example .env
yarn install
yarn add hardhat-gas-reporter
echo 'import "hardhat-gas-reporter";' >> hardhat.config.ts
yarn compile
npx --no hardhat test
```

Gas report:
```
·---------------------------|---------------------------|-------------|-----------------------------·
|   Solc version: 0.8.11    ·  Optimizer enabled: true  ·  Runs: 800  ·  Block limit: 30000000 gas  │
····························|···························|·············|······························
|  Methods                                                                                          │
···············|············|·············|·············|·············|···············|··············
|  Contract    ·  Method    ·  Min        ·  Max        ·  Avg        ·  # calls      ·  eur (avg)  │
···············|············|·············|·············|·············|···············|··············
|  Deployments              ·                                         ·  % of limit   ·             │
····························|·············|·············|·············|···············|··············
|  PRBMathSD59x18Mock       ·          -  ·          -  ·    2031637  ·        6.8 %  ·          -  │
····························|·············|·············|·············|···············|··············
|  PRBMathSD59x18TypedMock  ·          -  ·          -  ·    2385256  ·          8 %  ·          -  │
····························|·············|·············|·············|···············|··············
|  PRBMathUD60x18Mock       ·          -  ·          -  ·    1798736  ·          6 %  ·          -  │
····························|·············|·············|·············|···············|··············
|  PRBMathUD60x18TypedMock  ·          -  ·          -  ·    2105947  ·          7 %  ·          -  │
·---------------------------|-------------|-------------|-------------|---------------|-------------·
```

The `|  Contract    ·  Method    ·` part normally is followed by rows for specific methods. Here there are none and `Deployments` are listed immediately afterwards. There's an option to show methods that are never called:

```
config.gasReporter = {
    enabled: true,
    onlyCalledMethods: false,
};
```
with that, the plugin says that the methods from the mock are never called even though in tests they are:
```
·------------------------------------------|---------------------------|-------------|-----------------------------·
|           Solc version: 0.8.11           ·  Optimizer enabled: true  ·  Runs: 800  ·  Block limit: 30000000 gas  │
···········································|···························|·············|······························
|  Methods                                                                                                         │
····························|··············|·············|·············|·············|···············|··············
|  Contract                 ·  Method      ·  Min        ·  Max        ·  Avg        ·  # calls      ·  eur (avg)  │
····························|··············|·············|·············|·············|···············|··············
|  PRBMathSD59x18Mock       ·  doAbs       ·          -  ·          -  ·          -  ·            0  ·          -  │
····························|··············|·············|·············|·············|···············|··············
|  PRBMathSD59x18Mock       ·  doAvg       ·          -  ·          -  ·          -  ·            0  ·          -  │
····························|··············|·············|·············|·············|···············|··············
|  PRBMathSD59x18Mock       ·  doCeil      ·          -  ·          -  ·          -  ·            0  ·          -  │
····························|··············|·············|·············|·············|···············|··············
|  PRBMathSD59x18Mock       ·  doDiv       ·          -  ·          -  ·          -  ·            0  ·          -  │
····························|··············|·············|·············|·············|···············|··············
...
```

**Comment by paulrberg** [comment]
Hey @cameel! This is a known issue with `hardhat-gas-reporter`:

https://github.com/cgewecke/hardhat-gas-reporter/issues/59

Internal functions are unfortunately not included in the output.

> ... or if PRBMath is just doing things the way that's not compatible with it. If it's the latter, it might be a good idea to adjust the code to make it compatible.

I can't mark the PRBMath functions as external or public because I intend to keep this library inlineable.

The solution for now is to do what I did in the [test/gas-estimations](https://github.com/paulrberg/prb-math/tree/test/gas-estimations) branch, which is to add a bunch of `console.log` statements, run each function test set individually, and parse that manually in a Markdown file. It's a rather laborious process and the reason why I haven't been continuously updating the gas costs in the README.

Pinging @cgewecke in case he has some spare time to enable gas reports for internal pure functions in `hardhat-gas-reporter`.

**Comment by cameel** [comment]
> I can't mark the PRBMath functions as external or public because I intend to keep this library inlineable.

I didn't really expect it to list the internal functions :) Doing that would be pretty hard because they might not even exist after optimization as you pointed out. But you have `doAbs()`, `doAvg()`, etc. in your mocks and these are external. They should be listed in the report. For me they're just fine as a proxy for benchmarking the actual functions. In my use case I'm only really interested in relative changes to gas, not absolute values.

So are you perhaps just filtering them out in some way because you're only interested in seeing the values from the library functions? Or is `hardhat-gas-reporter` maybe designed to automatically filter out functions from mocks?

**Comment by cameel** [comment]
Ah, I see it. They're `pure` so apparently they're executed without an explicit transaction. That explains why they're not listed.

I think this one should actually be solvable for `hardhat-gas-reporter`. I think the eth client should be reporting the gas used in some way even if it just simulates the function locally...

**Comment by cgewecke** [comment]
Yeah agree - we should be detecting `eth_call` and fetching the usage here by running `estimateGas`. This would be a big improvement.

**Comment by cameel** [comment]
ok, I guess we'll have to wait for that feature then. Thanks for the explaining this anyway!

Since this is not really something that needs any action on prb-math side, I'm closing the issue.
