### ISSUE TITLE
`before all` hook sometimes times out in `PRBMath Solidity` test

### ISSUE THREAD

**Issue by cameel** [paulrberg/prb-math#71]
I have seen this fail at least twice ([972388](https://app.circleci.com/pipelines/github/ethereum/solidity/22165/workflows/590bfab7-3e2e-47c4-aaba-49bb55ccf483/jobs/972388), [970845](https://app.circleci.com/pipelines/github/ethereum/solidity/22131/workflows/506bdd96-fc63-448a-aa62-2b0c2ea2ec90/jobs/970845)) when running tests:
```
  298 passing (3s)
  1 failing

  1) PRBMath Solidity
       "before all" hook in "PRBMath Solidity":
     Error: Timeout of 2000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves. (/tmp/ext-test-PRBMath-Z8KoNI/ext/test/contracts/index.test.ts)
```

Either something's going wrong there or the test just needs a longer timeout. I've seen a similar problem recently in Euler and there it's just a question of tests taking too long (https://github.com/euler-xyz/euler-contracts/issues/97).

**Comment by paulrberg** [comment]
Hmm, I think this is just Hardhat having changed the default maximum running time for tests. I bumped into the same issue in [one of my other projects](https://github.com/paulrberg/hardhat-packager/commit/93e5daa26830a7541c7037a19573420527fa506e) and I solved it by bumping the timeout to 30 seconds.

Can you pull from `main` and see it if it works now?

**Comment by cameel** [comment]
I haven't seen it fail again so far and it's always running on a fresh checkout from `main` so looks like it's fixed. In that case I'm closing this and I'll reopen if I bump into it again. Thanks!
